### ISSUE TITLE
No corresponding papers can be found

### ISSUE THREAD

**Issue by xinyanghuang7** [slei109/PATNet#1]
Dear author, thank you very much for providing the code of your paper. The title of your paper is very exciting and attractive to me. 

But now I have a problem that I **can't find your paper on the Internet**. I hope you can provide the content or links of this paper. 

Thank you very much.

**Comment by slei109** [comment]
Hi there, Thanks for your interest in our work. We have not uploaded the paper to arxiv so far. It'll be available after ECCV :)

**Comment by xinyanghuang7** [comment]
Thank you very much for your timely reply. I just finished reading your paper today. It inspired me a lot! Congratulations and admiration again!

向你学习！
