### ISSUE TITLE
Qusetion aboout Dataset

### ISSUE THREAD

**Issue by 1yanzu1** [slei109/PATNet#10]
Dear author,sorry to bother you.I hava some questions to ask you.why can i find the picture.Athough my dataset from your link.The error is FileNotFoundError: [Errno 2] No such file or directory: 'D:/My_data/VOCdevkit/VOC2012/SegmentationClass/2008_006950.png'

**Comment by slei109** [comment]
It seems that the training data cannot be found, you need to check if the data path matches the one you set.
