### ISSUE TITLE
Preprocessing of Deepglobe Dataset

### ISSUE THREAD

**Issue by niejiahao1998** [slei109/PATNet#11]
Hi Shuo,
It seems that you classified images in Deepglobe into six category subfolders.
Could you please release the code for that step?
Thank you very much.

**Comment by slei109** [comment]
Hi Jiahao, 
You can check the preprocessing code of Deepglobe dataset and the class information about ISIC dataset under the data folder.

**Comment by niejiahao1998** [comment]
Yes. I know.
The problem is that you classify each category of the Deepglobe image into different subfolders, as well as annotations.
The structure of the original dataset downloaded from your provided link is below:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/60549451/223159035-1fd306e4-d641-4637-8f85-28d3d3b24df7.png">
It is very different from what is in your code.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/60549451/223160099-e98663cd-e1b3-469e-adcd-fbe2b9365c4c.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/60549451/223160196-e4f2b0bd-5f7b-4213-a644-4919867d471d.png">


In your provided preprocess.py file, the code crops images into smaller pieces and filters out some useless ones.
But the most critical step, which uses the original mask to divide original data into different categories, is not included.
Could you please provide it?

**Comment by slei109** [comment]
You mean the corresponding id in folder for each category? We evaluate the model with the average performance of all six categories, so it doesn't matter what the category corresponds to.

**Comment by niejiahao1998** [comment]
Yes. I know it doesn't matter what the category corresponds to.
But I am not sure how to generate different masks for different categories.
Do you directly split each mask into six different ones?
Could you please provide the code which divides each original mask into different six?
Thank you very much.

**Comment by slei109** [comment]
We generted binary mask for each class. I updated the preprocessing.py for details.

**Comment by niejiahao1998** [comment]
Thank you very much.

**Comment by sagacious-cao** [comment]
> Hi Shuo, It seems that you classified images in Deepglobe into six category subfolders. Could you please release the code for that step? Thank you very much.

Have you solved the problem?
It seems that images and masks are both divided into 6 categories in deepglobe.py like:
img_paths = sorted([path for path in glob.glob('%s/*' % os.path.join(self.base_path, cat, 'test', 'origin'))]) (for images)
ann_path = os.path.join(self.base_path, query_name.split('/')[-4], 'test', 'groundtruth') (for masks)

But only masks are divided into 6 categories in preprocess.py.
How can I divided images into corresponding categories?
 Thanks!
