### ISSUE TITLE
Some details of the paper

### ISSUE THREAD

**Issue by canglangzhige** [slei109/PATNet#12]
Thanks for your excellent work!
Where can I find the supplementary material ?
What is the "--niter"  on the  PASCAL VOC dataset? The default in the code is 2000.
Can one-shot segmentation results be visualized?
Thanks!

**Comment by slei109** [comment]
Thanks for your interest in our work.
I post the link of supplementary material on the Readme file, or you can check the supp via https://slei109.github.io/papers/eccv_cdfss_supp.pdf
"--niter" denotes the epoch, we adopt the early stop training strategy, so the default is 2000. You can set it with your dataset.
Some of qualitive results of one-shot task are shown in Fig5 in the paper.
