### ISSUE TITLE
Question about the training

### ISSUE THREAD

**Issue by canglangzhige** [slei109/PATNet#13]
Thanks for your work!
I have a question that I would like to have answered from you：

Configuration of the training network:
8 x 2080 Ti GPUs
batch size = 32
nworker = 12 (0, 2, 8 were also tested)

I train the [HSNet,](https://github.com/juhongm999/hsnet) and the speed can be fast. The GPU-Util is high(about 50%). I can complete an epoch in a few minutes.
But the training speed is particularly slow when I perform your code with the same configuration. GPU-Util fluctuates a lot (occupancy from 1%-50%), and it takes 90 minutes to train one epoch!
Moreover, even training your network with one 2080 Ti GPU, the GPU-Util fluctuates greatly.
What is the reason for this problem?
Thanks!

**Comment by slei109** [comment]
Our method has additional layers to train and calculation steps, so it will spend more time than HSNet. But it shouldn't take so long time like yours. It's a little weird. Not sure what's the problem. I just rerun the code on another server, it can finish one training epoch within 10 minimutes on one 3090 GPU. The batch size is 20 and the memory cost is around 22294 MB.
