### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by al3ms** [slei109/PATNet#14]
Hello dear
I am trying to run your code but I get this error:

```
  File "/usr/local/lib/python3.9/dist-packages/PIL/Image.py", line 3030, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '../VOCdevkit/VOC2012/JPEGImages/2010_004045.jpg'
```

1- Is there any problem with the folder "VOCdevkit" location? I uploaded it on the same folder where I cloned your repository.
2- Is there a pretrained model?
3- Could you please explain how to run your code using different training dataset?

Thank you very much!

**Comment by slei109** [comment]
Thanks for your interest in our work.
1. The default path of VOCdevkit is in the previous directory of the repository. If you put it in the same folder, you should revise the datapath accordingly, changing the datapath from '../VOCdevkit' to './VOCdevkit'
2. Sorry, we didn't upload the pretrained model.
3. The current version only supports training with PASCAL dataset. If you want to use your own dataset as the training data, you can revise Line 58, 59, 85, and 86 to change training dataset.
