### ISSUE TITLE
Code and paper seem inconsistent

### ISSUE THREAD

**Issue by Lzuze** [slei109/PATNet#15]
Thanks for releasing the code！
But I found that the implementation of the transformation matrix and the paper description seem to be inconsistent.
In your code, the matrix was implemented as:
`P = torch.matmul(torch.pinverse(C), R)`
but in your paper, the matrix were calculated as 
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/33783809/236981754-563d09c7-693e-4cea-9a58-a5a5f17a13d3.png">

Accordingly, the matrix should be implemented as: 
`P = torch.matmul(R, torch.pinverse(C))`.
It really confused me. Looking forward to your reply！

**Comment by slei109** [comment]
They are two different way to implement the same thing. It depends on the dimension of your W, P and A. Here, WP=A, the dimension of W is CxC, P is CxN and A is CxN. But in the implementation, for the convenience, the shape of R is NxC, thus P=torch.matmul(torch.pinverse(C), R). If you define the shape of R as CxN in your code, then you can implement P=torch.matmul(R,torch.pinverse(C)).
