### ISSUE TITLE
Dataset Structure of different dataset

### ISSUE THREAD

**Issue by al3ms** [slei109/PATNet#18]
Thank you for your work and continued support.

How should I structure my own datasets to work fine with minimal code changes? Could you explain please.

**Comment by al3ms** [comment]
This is my dataset structure it is simple:

Dataset Folder contains 4 sub-folders:
1- TrainVolumes 
2- TrainSegmentation
3- TestVolumes
4- TestSegmentation
Each of the above folders contains images of one task.
While I have N datasets for different tasks.

One more question I should ask it before: Should I change my dataset structure to work with minimal code changes or should I customise your code for my dataset?

**Comment by slei109** [comment]
I think you can write a data loader file for your dataset and then revise the dataset.py accordingly. That would be the easiest way.
