### ISSUE TITLE
Question about Deepglobe Dataset

### ISSUE THREAD

**Issue by sagacious-cao** [slei109/PATNet#19]
Thanks for your work!
It seems that images and masks are both divided into 6 categories in deepglobe.py like:
`img_paths = sorted([path for path in glob.glob('%s/*' % os.path.join(self.base_path, cat, 'test', 'origin'))])` (**for images**)
`ann_path = os.path.join(self.base_path, query_name.split('/')[-4], 'test', 'groundtruth')` (**for masks**)

But only masks are divided into 6 categories in preprocess.py. 
How can I divided images into corresponding categories?

**Comment by niejiahao1998** [comment]
The images and corresponding masks have the same index, then you can use the mask_file_name to match the corresponding images.
