### ISSUE TITLE
关于fss-1000的疑问

### ISSUE THREAD

**Issue by hhzxy** [slei109/PATNet#22]
File "..\PATNet-master\data\fss.py", line 83, in sample_episode
    class_sample = self.categories.index(query_name.split('/')[-2])
IndexError: list index out of range

感谢您的工作!
我把验证集的数据准备好之后运行train.py出现上述错误，不知道是哪里出错了，想请问一下

**Comment by slei109** [comment]
It seems that something wrong with your file name of fss-1000 dataset. The default setting should be test split of fss-1000 dataset.
