### ISSUE TITLE
How to freeze randomness during testing for reproducibility

### ISSUE THREAD

**Issue by JIaqiYang78** [slei109/PATNet#26]
Hello, I have a question. When I want to test on four benchmark, how can I freeze randomness during testing for reproducibility. Should I setting the parameter 'shuffle = false' ? And how did you split the test data for these four benchmark data sets?

**Comment by slei109** [comment]
Hi, for the randomness, the default setting is freeze the seed to 0. You may refer to Line 22 in train.py and Line 18 in test.py.
For the test split, since there is no training data for those four datasets, no test data split is needed. Just random sample the support and query set for testing.
