### ISSUE TITLE
About deepglobe and isic dataset

### ISSUE THREAD

**Issue by King-king424** [slei109/PATNet#28]
Can you provide more detailed guidance on how to properly load deepglobe and isic datasets?
1. isic 
Is it correct to classify ISIC Training Images into three categories according to class_id.csv?
![image](https://github.com/slei109/PATNet/assets/39642013/0e45e041-4a61-4a0b-93cf-c93815dd2a22)

2.deepglobe
After the preprocess.py processing, the chunked and filtered Image and label are obtained.
![image](https://github.com/slei109/PATNet/assets/39642013/f829e079-8653-4890-a999-81ecb0c04e9b)
![image](https://github.com/slei109/PATNet/assets/39642013/4c487410-2344-4be0-be36-cec179c6e131)

How do I use your code to load the processed data?
![image](https://github.com/slei109/PATNet/assets/39642013/5db3bc16-ff11-4b2d-8135-fe966801c2e0)
![image](https://github.com/slei109/PATNet/assets/39642013/2e7f3392-96f9-4b13-a6d4-6d82d3fef692)

**Comment by slei109** [comment]
Each dataset has its own data loading process. In data/dataset.py, it calls the class based on the dataset. The high level idea of the loading process is that we first establish the category information for each image/mask in metadata_classwise function. And then random sample the image ids for support set and query set. Finally load the images and masks with sampled ids.

For the ISIC dataset, yes, there are 3 classes in this dataset. And we only need to split image data into three groups and the code can find its corresponding annotation data during loading process.

For the Deepglobe dataset, if you utilize our code directly, your datapath to Deepglobe dataset should be: 'yourdatapath/Deepglobe/1/', 'yourdatapath/Deepglobe/2/', etc.
And for each class:
annotation data of class 1 'yourdatapath/Deepglobe/1/test/groudtruth' 
image data of class 1 'yourdatapath/Deepglobe/1/test/origin'
