### ISSUE TITLE
We adopted early stop strategy during training. So it didn't run 2000 epochs. You can reset it to work with your dataset.

### ISSUE THREAD

**Issue by TungChintao** [slei109/PATNet#29]
We adopted early stop strategy during training. So it didn't run 2000 epochs. You can reset it to work with your dataset.

_Originally posted by @slei109 in https://github.com/slei109/PATNet/issues/7#issuecomment-1399691005_
            Thank you for your answer. But I did not see the early stop strategy in the code you provided. Do I need to add this myself？

**Comment by slei109** [comment]
We may miss it when release the code. Yep, you can add it by yourself. It's very easy, just add it to validation step during the training process. Or you can reduce the default training epochs based on your emprical results.
