### ISSUE TITLE
Preprocessing of Deepglobe

### ISSUE THREAD

**Issue by xinyanghuang7** [slei109/PATNet#3]
Dear Author!
Thank you for providing the code, but I encountered some problems reproducing your article. 

About the preprocessing of the **Deepglobe** dataset you mentioned in the paper, that is, _**to increase the number of testing images and reduce the size of images, we cut each image into 6 pieces. As the categories labeled in this dataset have no regular shape, the cutting operation has little effect on the segmentation. After filtering the single class images and the'unknown'class, we get 5,666 images to report the results and each image has 408 × 408 pixels,**_ I can't reproduce it. 

I **hope you can supplement the code.** This will help me learn your article a lot. 
Thank you!

**Comment by slei109** [comment]
Thanks for your interest. I just uploaded the preprocess.py file under the data folder. We filter the single-class images and the images whose foreground percent is small than 0.048.
