### ISSUE TITLE
Problem running program on non cuda:0

### ISSUE THREAD

**Issue by TungChintao** [slei109/PATNet#30]
When I tried to run the program on a GPU other than cuda: 0, for example, on cuda: 4, the program reported an error：tensors were found at cuda:0 and cuda:4.
setting and result are here
![QQ截图20230905201445](https://github.com/slei109/PATNet/assets/62784962/8ff271e7-3f9b-4559-8b08-9f6d44dca4c6)
![QQ截图20230905201631](https://github.com/slei109/PATNet/assets/62784962/cf8155e0-bde4-46d5-90ca-27be772faded)

**Comment by slei109** [comment]
The default setting for data is on cuda0. You should revise the cuda id for data as well. It can be revised in Common/utils.py to_cuda() function.
