### ISSUE TITLE
test detail

### ISSUE THREAD

**Issue by King-king424** [slei109/PATNet#31]
![image](https://github.com/slei109/PATNet/assets/39642013/bdb16379-5087-47f7-8ebc-d45aac2486f1)
![image](https://github.com/slei109/PATNet/assets/39642013/828008b5-8458-45d9-afb0-fcbdf309f24a)
1.我应该将num改为1200吗?

**Comment by slei109** [comment]
Yes, that's the default setting. It's okay to revise here or you'd better revise the setting when you initialize the dataset.
