### ISSUE TITLE
Could you provide the processed DeepGlobe dataset?

### ISSUE THREAD

**Issue by King-king424** [slei109/PATNet#33]
According to the preprocess.py you provided, the number of processed images is 9175 instead of 5666.
I don't know why this is the case. To facilitate comparison with your work, hope you could provide the processed dataset.

**Comment by King-king424** [comment]
If you can't provide the dataset directly, could you reconfirm that the code you provided makes the final dataset consistent with the description of the paper?

**Comment by slei109** [comment]
I just upload the processed data, you can download via https://drive.google.com/file/d/10qsi1NRyFKFyoIq1gAKDab6xkbE0Vc74/view?usp=sharing

**Comment by zhutianlee** [comment]
the number of processed images in the Link is not 5666（describe in paper）this is why
