### ISSUE TITLE
Could you provide the fine-tune code?

### ISSUE THREAD

**Issue by TungChintao** [slei109/PATNet#38]
I tried to use TFI but couldn't achieve the results of your paper, could you provide the fine-tune code?

**Comment by slei109** [comment]
We provided the key code named finetune_reference() in the patnet.py. You can call it directly.

**Comment by TungChintao** [comment]
> We provided the key code named finetune_reference() in the patnet.py. You can call it directly

I've called it in test.py to finetune the ref_layer but I can't achieve the results of your paper. Could you directly provide the finetune.py?
