### ISSUE TITLE
The performance of PATNet without test-time finetuing

### ISSUE THREAD

**Issue by King-king424** [slei109/PATNet#39]
I used the code you provided as well as the dataset to reproduce PATNet. Without fine-tuning, the difference on DeepGlobe's dataset is a bit large. Here's what I reproduced, and the inference was averaged over 5 different random seeds.
The performance of other datasets is quite similar, but the deepglobe dataset is quite different. I wonder if there is an error with the dataset provided?
deepglobe
![image](https://github.com/slei109/PATNet/assets/39642013/bf91cc72-9389-4155-88f1-a7f20dca7847)
fss-1000
![image](https://github.com/slei109/PATNet/assets/39642013/d0637ab0-51f6-4a0a-88ed-196191019186)
isic
![image](https://github.com/slei109/PATNet/assets/39642013/0380585a-e3f7-4ab1-bc29-0c3568d3d3d7)
chest x-ray
![image](https://github.com/slei109/PATNet/assets/39642013/ef2fc13b-b6c2-4d0a-bbc7-9df1c49b5816)
This is the ablation experiment in your paper on test-time finetuing.
![image](https://github.com/slei109/PATNet/assets/39642013/f4e6d588-15d5-4986-84b8-1f17f2ef6495)

**Comment by slei109** [comment]
Have you checked your visualization output on Deepglobe? The dataset looks good, and I remembered that the model had pretty stable performance on DeepGlobe.
