### ISSUE TITLE
The Task-Adaptive Fine-Tuning Inference (TFI) coding

### ISSUE THREAD

**Issue by Bibaba-King** [slei109/PATNet#45]
Thanks for your excellent work！
I couldn't find any code for calling **TFI**，only **finetune_reference** can be found。I want to know if you forgot to write TFI related code in test.py？

**Comment by slei109** [comment]
Thanks for your interest. We didn't release test_finetune.py due to the undergoing project. We provided finetune_reference for reproducing the results.
