### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by RRW168** [slei109/PATNet#6]
Hi, sorry to bothering you.
I have some question about the deeplobe dataset and isic, I download these dataset and processed them but it didn't work.
![1670653384037](https://user-images.githubusercontent.com/110797602/206835353-dc69d12d-c6dd-42d8-972b-6414e337773d.png)
The datasets  seem to be classified into various folders but I don't kown how to classfy them. 
So could you give me the deeplobe and isic datasets that you directly used in the paper? Thank you!

Best regard

**Comment by slei109** [comment]
Thanks for your interest. Due to the licensing agreement, we cannot release the processed data. Only Deepglobe dataset need preprocess and I've released the code for it. For ISIC dataset, you can download it directly via the link I provided.
