### ISSUE TITLE
Question about ISIC dataset

### ISSUE THREAD

**Issue by neymar-jr** [slei109/PATNet#9]
![image](https://user-images.githubusercontent.com/45635363/217704061-c6bcccbc-749f-4596-8f60-77bc6b73afe0.png)
![image](https://user-images.githubusercontent.com/45635363/217704103-89c50773-13d7-48f3-a870-fe0383a97601.png)
![image](https://user-images.githubusercontent.com/45635363/217704606-2128eaee-4f59-41fa-bed4-6586360bb17e.png)
Sorry to bother you. The raw ISIC dataset is just pictures with serial numbers. It seems that you have categoried the ISIC dataset into three folders named 1, 2, 3. Could you please provide the related code. Thanks!

**Comment by neymar-jr** [comment]
![image](https://user-images.githubusercontent.com/45635363/217716043-770482e7-9b7d-4257-9f81-c9f6891b1a25.png)
![image](https://user-images.githubusercontent.com/45635363/217716307-6576e442-fa22-49ec-8400-c782ccb97611.png)

As for Chest X-ray dataset, query_name is truncated into query_id which makes it mismatch with raw filename. Maybe you have preprocessed the dataset. Could you please release the related code. It runs with the error occured as below.

Backbone # param.: 23561205
Learnable # param.: 2580968
Total # param.: 26142173
# available GPUs: 4
Total (trn) images are : 13680
Total (val) images are : 704
[Epoch: 00] [Batch: 0001/0684] L: 0.70106  Avg L: 0.70106  mIoU: 10.49  |  FB-IoU:  9.96
[Epoch: 00] [Batch: 0051/0684] L: 0.41696  Avg L: 0.49223  mIoU:  5.48  |  FB-IoU: 40.79
[Epoch: 00] [Batch: 0101/0684] L: 0.40772  Avg L: 0.45406  mIoU: 21.85  |  FB-IoU: 49.89
[Epoch: 00] [Batch: 0151/0684] L: 0.38530  Avg L: 0.43818  mIoU: 26.91  |  FB-IoU: 52.82
[Epoch: 00] [Batch: 0201/0684] L: 0.38113  Avg L: 0.42876  mIoU: 28.79  |  FB-IoU: 53.88
[Epoch: 00] [Batch: 0251/0684] L: 0.30136  Avg L: 0.41698  mIoU: 32.07  |  FB-IoU: 55.74
[Epoch: 00] [Batch: 0301/0684] L: 0.33354  Avg L: 0.40599  mIoU: 33.60  |  FB-IoU: 56.91
[Epoch: 00] [Batch: 0351/0684] L: 0.33840  Avg L: 0.39849  mIoU: 35.22  |  FB-IoU: 57.87
[Epoch: 00] [Batch: 0401/0684] L: 0.32931  Avg L: 0.39126  mIoU: 36.44  |  FB-IoU: 58.71
[Epoch: 00] [Batch: 0451/0684] L: 0.45022  Avg L: 0.38523  mIoU: 37.42  |  FB-IoU: 59.42
[Epoch: 00] [Batch: 0501/0684] L: 0.32332  Avg L: 0.38110  mIoU: 38.41  |  FB-IoU: 60.01
[Epoch: 00] [Batch: 0551/0684] L: 0.36951  Avg L: 0.37762  mIoU: 39.56  |  FB-IoU: 60.61
[Epoch: 00] [Batch: 0601/0684] L: 0.36883  Avg L: 0.37382  mIoU: 40.39  |  FB-IoU: 61.10
[Epoch: 00] [Batch: 0651/0684] L: 0.32287  Avg L: 0.37037  mIoU: 40.98  |  FB-IoU: 61.46

*** Training [@Epoch 00] Avg L: 0.36717  mIoU: 41.49   FB-IoU: 61.78   ***

Traceback (most recent call last):
  File "/home/liuxuanchen/Develop/cross-domain/PATNet/train.py", line 111, in <module>
    val_loss, val_miou, val_fb_iou = train(epoch, model, dataloader_val, optimizer, training=False)
  File "/home/liuxuanchen/Develop/cross-domain/PATNet/train.py", line 27, in train
    for idx, batch in enumerate(dataloader):
  File "/home/liuxuanchen/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/liuxuanchen/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/liuxuanchen/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/liuxuanchen/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/liuxuanchen/Develop/cross-domain/PATNet/data/lung.py", line 35, in __getitem__
    query_img, query_mask, support_imgs, support_masks = self.load_frame(query_name, support_names)
  File "/home/liuxuanchen/Develop/cross-domain/PATNet/data/lung.py", line 65, in load_frame
    query_img = Image.open(os.path.join(self.img_path, os.path.basename(query_id))).convert('RGB')
  File "/home/liuxuanchen/anaconda3/envs/torch/lib/python3.9/site-packages/PIL/Image.py", line 3131, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/liuxuanchen/crossdomain/ChestX-ray/LungSegmentation/CXR_png/MCUCXR_0.png'

**Comment by slei109** [comment]
Thanks for your interest. I just uploaded the class_id.csv file under the data/isic folder. You can use it to split ISIC data into 3 classes. 
And for LungSegmentation data, there's no preprocessing. We utilize the mask information in "masks" folder to find the corresponding image in "CXR_png" folder. Ideally, it won't try to find any images starting with "MCUCXR" because there's no MCUCXR* in masks folder. You may need to double check your data path setting and code.

**Comment by PimiYvan** [comment]
I got the same issue for lungSegmentation, and I understood that problem, in fact when we download that new lung dataset from kaggle, it contains other file (MCUCXR*), and it is those file which is making the errors 

`FileNotFoundError: [Errno 2] No such file or directory: '/data/liuxuanchen/crossdomain/ChestX-ray/LungSegmentation/CXR_png/MCUCXR_0.png'`

for fixing that issue we have to remove all the MCUCXR* file, or we can update the code for managing the file in the Lung dataset (data/lung.py). we have to update the function build_img_metadata_classwise. 
this is my code, and it works 

`    
def build_img_metadata_classwise(self):
        img_metadata_classwise = {}
        for cat in self.categories:
            img_metadata_classwise[cat] = []

        for cat in self.categories:
            img_paths = sorted([path for path in glob.glob('%s/*' % self.ann_path)])
            for img_path in img_paths:
                base_name = os.path.basename(img_path)
                if "MCUCXR" not in base_name and base_name.split('.')[1] == 'png':
                    img_metadata_classwise[cat] += [img_path]
                # if os.path.basename(img_path).split('.')[1] == 'png':
                #     img_metadata_classwise[cat] += [img_path]
        return img_metadata_classwise
`
        
it just ignored every file which contains "MCUCXR' in it path.
